namespace PT.PM.Common.Nodes
{
    public enum NodeType
    {
        RootNode = 500,

        // Global Scope
        Attribute = 400,
        AttributeSection,
        Comment,
        Constraint,
        DelegateDeclaration,
        ExternAliasDeclaration,
        NamespaceDeclaration,
        NewLineNode,
        PreProcessorDirective,
        TextNode,
        TypeDeclaration,
        TypeParameterDeclaration,
        UsingAliasDeclaration,
        UsingDeclaration,
        WhitespaceNode,

        // Type Members
        Accessor = 300,
        ConstructorDeclaration,
        DestructorDeclaration,
        EnumMemberDeclaration,
        EventDeclaration,
        FieldDeclaration,
        FixedFieldDeclaration,
        FixedVariableInitializer,
        IndexerDeclaration,
        MethodDeclaration,
        OperatorDeclaration,
        ParameterDeclaration,
        PropertyDeclaration,
        VariableInitializer,

        // Body
        BlockStatement = 200,
        BreakStatement,
        ContinueStatement,
        DoWhileStatement,
        EmptyStatement,
        ExpressionStatement,
        ForeachStatement,
        ForStatement,
        GotoStatement,
        IfElseStatement,
        LabelStatement,
        ReturnStatement,
        SwitchStatement,
        SwitchSection,
        CaseLabel,
        ThrowStatement,
        TryCatchStatement,
        CatchClause,
        UncheckedStatement,
        UsingStatement,
        VariableDeclarationExpression,
        WithStatement,
        WhileStatement,
        YieldBreakStatement,
        YieldReturnStatement,

        // Expression
        AnonymousMethodExpression = 100,
        AnonymousTypeCreateExpression,
        ArrayCreationExpression,
        ArrayInitializerExpression,
        AssignmentExpression,
        BaseReferenceExpression,
        BinaryOperatorExpression,
        CastExpression,
        ConditionalExpression,
        DefaultValueExpression,
        DirectionExpression,
        ErrorExpression,
        IdentifierExpression,
        IndexerExpression,
        InvocationExpression,
        IsExpression,
        LambdaExpression,
        MemberReferenceExpression,
        NamedArgumentExpression,
        NamedExpression,
        NullLiteral,
        ObjectCreateExpression,
        ParenthesizedExpression,
        PointerReferenceExpression,
        PrimitiveExpression,
        QueryExpression,
        SizeOfExpression,
        StackAllocExpression,
        ThisReferenceToken,
        TypeOfExpression,
        TypeReferenceExpression,
        UnaryOperatorExpression,
        UncheckedExpression,
        UndocumentedExpression,

        // Literals
        Literal = 1,
        StringLiteral,
        TypeToken,
        TypeTypeLiteral,
        ModifierLiteral,
        IdToken,
        FloatLiteral,
        BooleanLiteral,
        IntLiteral,
        ClassType,
        Modifier,
        ParameterModifierLiteral,
        BinaryOperatorLiteral,
        UnaryOperatorLiteral,
        CommentLiteral,

        // Specific
        AsExpression,
        CheckedStatement,
        CheckedExpression,
        FixedStatement,
        LockStatement,
        CSharpParameterDeclaration,
        UnsafeStatement,

        // Collection
        Collection,
        ArgsNode,
        EntitiesNode,

        // Artificial
        MultichildExpression,
        StatementDeclaration,
        TypeDeclarationStatement,
        WrapperStatement,
        NotImplementedNode,
        WrapperExpression,

        // Patterns
        PatternRootNode = 600,
        PatternVarDef,
        PatternVarRef,
        PatternStringLiteral,
        PatternIdToken,
        PatternIntLiteral,
        PatternBooleanLiteral,
        PatternExpressions,
        PatternExpression,
        PatternExpressionInsideExpression,
        PatternExpressionInsideStatement,
        PatternStatement,
        PatternMultipleExpressions,
        PatternMultipleStatements,
        PatternStatements,
        PatternComment,
        PatternIfElseStatement,
        PatternTryCatchStatement,
    }
}
